CREATE TABLE courses
(
    id           VARCHAR(255)                NOT NULL,
    created_date TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    updated_date TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    name         VARCHAR(255)                NOT NULL,
    code         VARCHAR(255)                NOT NULL,
    CONSTRAINT pk_courses PRIMARY KEY (id)
);

ALTER TABLE semesters
    DROP CONSTRAINT IF EXISTS FK_SEMESTERS_ON_YEAR;
ALTER TABLE semesters
    DROP COLUMN IF EXISTS year_id;

ALTER TABLE grades
    ADD COLUMN creator_id VARCHAR(255);
ALTER TABLE grades
    ADD CONSTRAINT FK_GRADES_ON_CREATOR FOREIGN KEY (creator_id) REFERENCES users (id);
ALTER TABLE grades
    ADD COLUMN year_id VARCHAR(255);
ALTER TABLE grades
    ADD CONSTRAINT FK_GRADES_ON_YEAR FOREIGN KEY (year_id) REFERENCES school_years (id);
ALTER TABLE grades
    ADD COLUMN  course_id VARCHAR(255);
ALTER TABLE grades
    DROP COLUMN IF EXISTS name;
ALTER TABLE grades
    ADD CONSTRAINT FK_GRADES_ON_COURSE FOREIGN KEY (course_id) REFERENCES courses (id);