CREATE TABLE IF NOT EXISTS grade_versions
(
    id           varchar(255)                NOT NULL PRIMARY KEY,
    created_date TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    updated_date TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    name         VARCHAR(255)                NOT NULL,
    creator_id   VARCHAR(255),
    user_id      VARCHAR(255),
    CONSTRAINT FK_GRADE_VERSIONS_ON_USERS FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT FK_GRADE_VERSIONS_ON_USERS_CREATOR FOREIGN KEY (creator_id) REFERENCES users (id)
);