server-socket:
  host: 0.0.0.0
  port: 8085

server:
  tomcat:
    relaxed-query-chars: [ '{','}' ]

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: mentorus.hcmus@gmail.com
    password: efvgwfusjkeboldf
    protocol: smtp
    tls: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
  data:
    mongodb:
      user: root
      password: password
      uri: mongodb://root:Lamgicopass1234@172.17.0.1:27017/mentordb?authSource=admin
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 856018113300-ttu1tcagqq87039njp3ljaa1u9djockp.apps.googleusercontent.com
            clientSecret: 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
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - openid
              - email
              - profile
          azure:
            clientId: d1aa2e7d-f499-49eb-890a-4ced56bd35a5
            clientSecret: ZLS8Q~ldy20YOD6phW__ZjMqw93IC9wZjWQK6b43
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            authorizationGrantType: authorization_code
            scope:
              - openid
              - profile
        provider:
          azure:
            authorizationUri: https://login.microsoftonline.com/40127cd4-45f3-49a3-b05d-315a43a9f033/oauth2/v2.0/authorize?prompt=select_account
            tokenUri: https://login.microsoftonline.com/40127cd4-45f3-49a3-b05d-315a43a9f033/oauth2/v2.0/token
            userInfoUri: https://graph.microsoft.com/oidc/userinfo
            jwk-set-uri: https://login.microsoftonline.com/40127cd4-45f3-49a3-b05d-315a43a9f033/discovery/v2.0/keys
            userNameAttribute: name
            userInfoAuthenticationMethod: header
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth?prompt=select_account

azure:
  active-directory:
    jwt-connect-timeout: 6789
    jwt-read-timeout: 6789

app:
  googleDrive:
    rootId: 1Nz9fca4S7eAVAogMBmLIP1Om0Bp3puIK
  auth:
    tokenSecret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1
    tokenExpirationMsec: 8640000000
    refreshTokenExpirationMsec: 172800000
    allowedDomains: student.hcmus.edu.vn,fit.hcmus.edu.vn
  cors:
    allowedOrigins: http://localhost:3000,http://localhost:8080
  oauth2:
    # After successfully authenticating with the OAuth2 Provider,
    # we'll be generating an auth token for the user and sending the token to the
    # redirectUri mentioned by the client in the /oauth2/authorize request.
    # We're not using cookies because they won't work well in mobile clients.
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect
      - http://localhost:8080/
      - mentorus://oauth2/redirect
      - https://admin-mentorus.hieucckha.me/auth/redirect
springdoc:
  packages-to-scan: com.hcmus.mentor.backend.controller
