server-socket:
  host: 0.0.0.0
  port: 8085

server:
  tomcat:
    relaxed-query-chars: [ '{','}' ]


spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: mentorus.hcmus@gmail.com
    password: efvgwfusjkeboldf
    protocol: smtp
    tls: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
  data:
    mongodb:
      user: root
      password: password
      uri: mongodb://root:password@localhost:27017/mentordb?authSource=admin
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 856018113300-orcmshnug3k11v61an2d782uta6etmd5.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - openid
              - email
              - profile
          azure:
            client-id: 8aad3f74-3cb6-45a8-99ed-583f684ea6bf
            client-secret: Mwo8Q~0EMFXprk7rFLVWK3dDFpMK3-.guexigcS4
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - openid
              - email
              - profile
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth?prompt=select_account
          azure:
            authorization-uri: https://login.microsoftonline.com/75b895ea-7ab4-4a2e-9d03-624765bf3801/oauth2/v2.0/authorize
            token-uri: https://login.microsoftonline.com/75b895ea-7ab4-4a2e-9d03-624765bf3801/oauth2/v2.0/token
            issuer-uri: https://login.microsoftonline.com/75b895ea-7ab4-4a2e-9d03-624765bf3801/v2.0

azure:
  active-directory:
    jwt-connect-timeout: 6789
    jwt-read-timeout: 6789

app:
  googleDrive:
    rootId: 1Nz9fca4S7eAVAogMBmLIP1Om0Bp3puIK
  auth:
    tokenSecret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1
    tokenExpirationMsec: 8640000000
    refreshTokenExpirationMsec: 172800000
    allowedDomains: student.hcmus.edu.vn,fit.hcmus.edu.vn
  cors:
    allowedOrigins: http://localhost:3000,http://localhost:8080
  oauth2:
    # After successfully authenticating with the OAuth2 Provider,
    # we'll be generating an auth token for the user and sending the token to the
    # redirectUri mentioned by the client in the /oauth2/authorize request.
    # We're not using cookies because they won't work well in mobile clients.
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect
      - http://localhost:8080/
      - mentorus://oauth2/redirect
springdoc:
  packages-to-scan: com.hcmus.mentor.backend.controller
